### ISSUE TITLE
Feature request: add method to toggle selected item

### ISSUE THREAD

**Issue by seranus** [d3lm/ngx-drag-to-select#46]
I need to add a specific set of items to selection based on their id. Later I use selected items for drag and drop.

**Comment by d3lm** [comment]
Hey @seranus, thanks for submitting this feature request!

Do I understand correctly that you need a way to toggle single items programatically?

One possible solution to this would be to introduce a function `select` on the `SelectContainer` that accepts a list of `SelectItemDirective` instances. The consumer of this lib would need to query the items that he wants to select and pass them to `selectContainer.select(myList)`. Internally this will then make sure that all these items are added to the `selectItems` list and also selects each select item accordingly.

Another approach would be to introduce a shared service between the select container and the select items. There could be a `select` method on the select item directive that broadcasts the event to the service and is then picked up by the select container which then adds the item to the list.

A third option would be to inject the select container into the select item directive but that results in tight coupling which is always not a good idea for several reasons. Yet, it's a valid solution.

@timdeschryver What do you think? Any other solution that comes to your mind?

I think this is a valid feature request.

Initially I thought this could be done with a two-way data binding, which is why I have introduced it on the `selectedItems` property in the first place. However, the value of this property is not always a list of select item directive instances but it can also be plain objects or even plain values if you want. This can be configured via the `dtsSelectItem` input property on the select item directive (see docs). I am not a big fan of the two-way data binding anyways as it breaks the unidirectional data flow. So I might remove this in favor of another solution. One problem with the two-way data binding approach would be that if it's just a list of id's for example, I'd need to find the correct select item instances, which shouldn't be done by the library as it's very use case specific.

I could imagine the service approach or the `select` method on the container component.

Any thoughts?

**Comment by timdeschryver** [comment]
Personally I don't like to make a templateRef and do `container.select()` in my code, but I think this would be the best solution you suggested @d3lm and this is also similar to what @seranus proposes.

I was thinking, but I don't know if this is a good solution or not, to add a `selected` property on `dtsSelectItem`. This can be confusing because you wouldn't need `selectedItems` anymore, the user has to maintain the selected items himself. As I'm writing this, I feel like this doesn't make sense because the user should be notified on every change (click, drag, ...) and update their list accordingly (think elm reducers).

To come back to why it doesn't make sense, I think it makes perfectly sense that the user has to maintain its own state and that a library "only" handles user interaction and dispatches events. But this would mean we would have to change a lot here 😅 .

This is my answer for now since it has been a while that I've been in ngx-drag-to-select, I might come with another answer later today..

**Comment by d3lm** [comment]
@timdeschryver Thanks for your reply!

Yes I can see where you're going with this and I like it. But this means a huge breaking change and if maintaining a list of selected items is such a common thing, which it is, I think the library can take care of this. The user can always maintain their own state / list if needed.

I also think that getting a reference to the select container to call `select` is not the most ideal solution. But from all the solutions I can think of, it's the best. By also exposing the list of select items on the container, the user at least doesn't need to query for those. So "all" you have to do is to get all items, check the value, find those you want to select and pass them back to the select container which takes care of selecting them.

Hmmm... not sure.

This would be essentially what @seranus also proposed which aligns with what I initially proposed. But again, not sure if this is the right way.

Maybe we can come up with some other solutions and then decide which works best.

**Comment by timdeschryver** [comment]
Would this mean that user has to work with `SelectItemDirective`?

Internally we'll have to but, what about something like the following:

```ts
// predicate to select items, internally we'll have to loop over all items and use `getValue()` to get the item's value and then we can use the predicate to filter out items
container.select(item => item.id === 5)

// another way would be to pass id's, and a id selector
container.select([5, 6, 9], item => item.id)
```

**Comment by d3lm** [comment]
That's an interesting idea! So basically the `select` method takes in a predicate and internally we loop over all select items and get the value. We would then filter out the items that need to be selected and finally we select all those items.

I like this idea very much!

**Comment by d3lm** [comment]
Would this work for you @seranus?

**Comment by seranus** [comment]
Sure as long as you expose the function to manually select I can work with anything, I don't need it atm but don't forget to also add unselect

**Comment by seranus** [comment]
@d3lm hi, I'd appreciate if you could give me an update on the state of this request

**Comment by d3lm** [comment]
@seranus I haven't had the time to work on this. I am happy to review a PR. I can try to work on this over the weekend. I'll have some spare time that I can dedicate to work on some open issues. I ll keep you posted. Or as I said, you could send in a PR too. I would really appreciate any help that I can get.

**Comment by d3lm** [comment]
PR #50 addresses this feature.
