### ISSUE TITLE
Disabling select with right click

### ISSUE THREAD

**Issue by RihamHazem** [d3lm/ngx-drag-to-select#53]
How can I disable select items with right click and enable it just for left click or drag?

**Comment by timdeschryver** [comment]
I think this isn't possible with the current API, correct me if I'm wrong @d3lm - see [container.component.ts#L156](https://github.com/d3lm/ngx-drag-to-select/blob/master/projects/ngx-drag-to-select/src/lib/select-container.component.ts#L156).

I also find it a bit strange that it's possible to click and drag with the right mouse button. Was this by design @d3lm ? If not, it's a simple fix; otherwise we'll have to make it customizable.

**Comment by d3lm** [comment]
Hey @RihamHazem, thank you for filing this issue! Being able to click and drag with the right mouse button was not by design. I think as @timdeschryver suggested we could either "fix" this or make it customizable.

Right now I don't really see the need to make it customizable and using the right mouse button for selecting is also very uncommon.

What do you think?
