### ISSUE TITLE
Import RxJS operators individually

### ISSUE THREAD

**Issue by MurhafSousli** [d3lm/ngx-drag-to-select#6]
Hi @d3lm, nice implementation!

Wouldn't it be better to import RxJS operators individually, to avoid including all operators?

```ts
import {
  switchMap,
  takeUntil,
  map,
  tap,
  filter,
  auditTime,
  mapTo,
  share,
  withLatestFrom,
  distinctUntilChanged
} from 'rxjs/operators';
```

**Comment by d3lm** [comment]
Thanks! What exactly do you mean by importing the operators individually?

**Comment by MurhafSousli** [comment]
Right, but that would import the whole functions
```ts
import { switchMap } from 'rxjs/operators/switchMap ';
import { takeUntil } from 'rxjs/operators/takeUntil ';
```
> Operators patched directly onto the prototype are not "tree-shakeable" by tools like rollup or webpack. Pipeable operators will be as they are just functions pulled in from modules directly.

**Comment by d3lm** [comment]
Yes, I think you are right. For a library this might be a better way of importing the operators because if someone uses this in a project that sits on an older version of Webpack or some other build tool that does not take care of tree shaking away the code that is not used, the bundle size will grow. This is because by default `rxjs/operators` will resolve to the CommonJS output of RxJS, as described [here](https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md#build-and-treeshaking).

While this is not a problem for the library bundle itself, because it does not embed any external dependency or node modules, but it can definitely be a problem for someone using this library.

**Comment by d3lm** [comment]
Just checked with some other open source library like `@ngrx/store` and they basically use the same way of importing operators as I do.

https://github.com/ngrx/platform/blob/master/modules/store/src/store.ts#L3

**Comment by fmalcher** [comment]
Interesting topic!
As long as you use pipeable operators and a Webpack build to bundle the library package I would stick with the current approach of importing from rxjs/operators.
Will your bundles become smaller when you import operators from their own separate paths? In fact, I've never used the deep imports until now.

**Comment by d3lm** [comment]
> As long as you use pipeable operators and a Webpack build to bundle the library package I would stick with the current approach of importing from rxjs/operators.

Yep, agreed. This is also what Ben said on Twitter and also what can be found in the docs. 

The bundle size will not be smaller as I am not embedding dependencies. The bundle basically only contains library related code.

**Comment by yashints** [comment]
I quite agree with @fmalcher. Importing from one place is much better. The bundle size has nothing to do with this as long as you have a good build process which only brings modules you need

**Comment by d3lm** [comment]
Closing this one as no action or refactoring is needed.
