### ISSUE TITLE
Selection rectangle persists if "alt" is pressed and held mid-drag

### ISSUE THREAD

**Issue by michaelbromley** [d3lm/ngx-drag-to-select#7]
Great lib and very nicely executed. Here's a kinda edge-case bug I found:

- Windows 10
- Chrome 65

### Reproduction 

1. Start dragging in the drag area
2. Press and hold the alt key
3. Release the mouse button to stop dragging
4. Release the alt key

### Expected
The selection rectangle disappears once the dragging has ended at step 3 above.

### Actual
The selection rectangle persists until a new drag is started.

### Demo
![2018-04-03_13-09-28](https://user-images.githubusercontent.com/6275952/38245919-532ce516-3740-11e8-9925-18061f953304.gif)

**Comment by d3lm** [comment]
Thank you for submitting this issue. I'll look into it ASAP.

**Comment by d3lm** [comment]
Maybe it makes sense to only start the dragging process if `alt` is not pressed. 

The idea here would be that pressing the `alt` key while dragging and selecting items will not interrupt the selection process. This means that, in order to disable the selection you have to press the `alt` key **before** you start dragging.

What do you think @michaelbromley?

**Comment by michaelbromley** [comment]
Yes that would make sense to me 👍

**Comment by d3lm** [comment]
Ok, this should be fixed now. Can you verify?

**Comment by michaelbromley** [comment]
Looks good! What a rapid resolution!
