### ISSUE TITLE
Support to ngModel

### ISSUE THREAD

**Issue by segux** [d3lm/ngx-drag-to-select#77]
I was trying to use dts-container as form control element but it's not developed for this purpouse.

How hard can be to add this functionality?

**Comment by d3lm** [comment]
Hey there! Thanks for using this lib and opening up this issue.

Regarding your question I'd say that the both the container nor the items are not meant to be form controls out of the box. This is something specific and less general use case. If you wish to integrate this into your forms I would suggest to wrap it in a custom form control and implement the `ControlValueAccessor`. This serves as a bridge between Angular's forms APIs and a native element or your own custom components.

Does that make sense?

**Comment by segux** [comment]
But you need an extra implementation and usually i used this component as form control.
right?

**Comment by d3lm** [comment]
Not really. I personally don't use this as a form control but their might be use cases for sure. But again, I try to avoid making this a custom form control out of the box because this means a more heavy implementation and less lightweight. This lib solely aims to provide drag-to-select functionality (single responsibility) and then you can build anything on top.
