### ISSUE TITLE
Use it with ng2-pdf-viewer

### ISSUE THREAD

**Issue by aammfe** [d3lm/ngx-drag-to-select#81]
Hello!!
is its possible to marry it with [ng2-pdf-viewer](https://github.com/VadimDez/ng2-pdf-viewer) and create PDF selection tool on steroids ..? 

I have opened an [Issue](https://github.com/VadimDez/ng2-pdf-viewer/issues/517#issue-488355740) if its possible please help me out !
Thanx.

**Comment by d3lm** [comment]
Hey there! I have not used that library myself so I don't really know what it takes, but do you have specific issues? I can try and answer your questions if you run into issues and maybe throw out some ideas how to fix them. I am happy to help.

**Comment by aammfe** [comment]
Hello!!
Thanx for reply 

some thing like this... 
https://www.newocr.com/ but a more advance.

here u can select only one area but what I m trying to do it would have multiple area selection.
and each selection could have a type.

**Comment by d3lm** [comment]
Hey, so I believe this has nothing to do with this library and is also outside its scope. I mean you can try to integrate it with a pdf-library and if you run into particular issues you can always come back here and we can discuss if we can do something about it. Because there are no actions to do, I am closing this issue for now.

**Comment by aammfe** [comment]
ok.. I will read ur code if I find any difficulty I will ask u here .. 
thanx :-)
