### ISSUE TITLE
doesn't work when scale the parent container

### ISSUE THREAD

**Issue by NeoZhao-cn** [d3lm/ngx-drag-to-select#83]
If you use 'transform: scale(x)' to scale your parent container, mouse pointer position is incorrect, and you can not select your items as you like.  For example, you can modify Demo Source app.component.html : class  'drag-area' div ' style :  transform-origin: 0px 0px 0px; transform: scale(0.6); then you can find this issue.

**Comment by NeoZhao-cn** [comment]
I have created a PR to fix this issue : #84

**Comment by d3lm** [comment]
Hey there! Thanks for opening up this issue. It's generally a good idea to first discuss this issue and find a solution before sending in a PR. Also, I would like to point you to the [Developer Guide](https://github.com/d3lm/ngx-drag-to-select/blob/master/DEVELOPERS_GUIDE.md) and the [Contributing Guide](https://github.com/d3lm/ngx-drag-to-select/blob/master/CONTRIBUTING.md). Just glimpsing at your PR, there's a couple of things that are not matching with the guides that I have mentioned. For example, empty commits and it's not clear what each commit does. There are also changes that I don't really understand and I am not sure why those changes have been made. This makes it very unlikely that the PR will be merged. Hence, as I said, it's good to first discuss the issue here and then together come up with a solution that works for all of us. To mention one thing, the `private` property in the `package.json` was changed from `false` to `true`. Also, the `--prod` flag was removed from the build script. Furthermore, there are ts-lint comments that I would like to avoid.

On top of this, the PR introduces `_getAllParentScrollEvent` and I am not sure why. In other issues we have discussed that it's not a good idea to query all parent elements like this. In addition, this is not really related to the scale issue, is it? 

Do you mind elaborating?

Another thing is that I am personally not happy with introducing yet another `Subject` for the scale. I think we should first try and evaluate other solutions, that maybe only involve the client bounding rect that we already have. Just throwing out ideas and I am not yet sure if that would work.

**Comment by NeoZhao-cn** [comment]
first ,thanks for your quickly response, and sorry for all the mistakes, cause this is my first time to commit a PR. as you mentioned , better to discuss the solution first. so i will send a demo to reproduce the issue. so we can focus on what's happening.

**Comment by NeoZhao-cn** [comment]
I have created a demo : https://stackblitz.com/edit/angular-9ouewa. Actually, there are two issues ,including scale and scoll, you can repreduce issues by steps follow:
issue 1:   click bottom 'zoom in' or 'zoom out', then drag mouse, the selectbox is in wrong position.
issue 2: reset zoom, then scroll 'drag area' down, and then drag mouse , the selectbox is in wrong position. 

about issue1 : as you can see in the PR, we can fix it by re-calculate mousePosition and selectBox when scale is changing.
about issue2: when scroll parent element, we need to update the selectContainer, because we cached selectContainer's BoundingClientRect. I don't know if there is a better solution. we can dicuss it.

**Comment by d3lm** [comment]
No, I personally have never worked on such application. But this library was not developed with a scalable or transformable canvas in mind. This goes beyond the capabilities and IMO responsibilities of this library. If you are dealing with a canvas that the user can zoom and do other things with, you might need to build a custom solution. But you can for sure find inspiration on how to build such feature for your application based on this library. Does that make sense?

**Comment by d3lm** [comment]
Closing this one for now.
